name       : ostree
version    : '2017.7'
release    : 5
source     :
    - https://github.com/ostreedev/ostree/releases/download/v2017.7/libostree-2017.7.tar.xz : c1e421f616da079a7671ac5ae765b97dca740429844283d47102e3135832a246
license    : LGPL-2.0
component  : system.utils
summary    : Git-like filesystem management
description: |
    Operating system and container binary deployment and upgrades
patterns   :
    - docs : /usr/share/man
builddeps  :
    - pkgconfig(e2p)
    - pkgconfig(fuse)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(liblzma)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libsystemd)
    - pkgconfig(mount)
    - pkgconfig(zlib)
    - gpgme-devel
    - libassuan-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # ostree is only used by flatpak in Solus, so nuke the unnecessary harmful bits.
    rm -rf $installdir/usr/{bin,lib}
    rm -rf $installdir/etc
