name       : ostree
version    : 2018.01
release    : 7
source     :
    - https://github.com/ostreedev/ostree/releases/download/v2018.1/libostree-2018.1.tar.xz : 8b5e3b80425b91c93aeb916bb047ee194aa138a9cf00ce173dcc0ebc0dd11f4b
license    : LGPL-2.0
component  : system.utils
summary    : Git-like filesystem management
description: |
    Operating system and container binary deployment and upgrades
patterns   :
    - docs : /usr/share/man
builddeps  :
    - pkgconfig(e2p)
    - pkgconfig(fuse)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(liblzma)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libsystemd)
    - pkgconfig(mount)
    - pkgconfig(zlib)
    - docbook-xml
    - gpgme-devel
    - libassuan-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # ostree is only used by flatpak in Solus, so nuke the unnecessary harmful bits.
    rm -rf $installdir/usr/{bin,lib}
    rm -rf $installdir/usr/share/bash-completion/
    rm -rf $installdir/etc
