name       : ostree
version    : 2018.8
release    : 9
source     :
    - https://github.com/ostreedev/ostree/releases/download/v2018.8/libostree-2018.8.tar.xz : beef6debb0065bf1dc7538cd036c5f0348ac102ca4ad6d8651feff146130a844
license    : LGPL-2.0-or-later
component  : system.utils
summary    : Git-like filesystem management
description: |
    Operating system and container binary deployment and upgrades
patterns   :
    - docs : /usr/share/man
builddeps  :
    - pkgconfig(e2p)
    - pkgconfig(fuse)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - docbook-xml
    - gpgme-devel
    - libassuan-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # Remove files only relevant to OSTree based OS images
    rm -r $installdir/etc/grub.d/
    rm -r $installdir/usr/lib
