name       : ostree
version    : 2016.15
release    : 2
source     :
    - https://github.com/ostreedev/ostree/releases/download/v2016.15/ostree-2016.15.tar.xz : 430178680bd0842dcfab66b780324f9e3cfa460799eec53166fa069e3396ecbd
license    : LGPL-2.0
component  : system.utils
summary    : Git-like filesystem management
description: |
    Operating system and container binary deployment and upgrades
patterns   :
    - docs : /usr/share/man
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(liblzma)
    - pkgconfig(zlib)
    - pkgconfig(e2p)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libarchive)
    - pkgconfig(mount)
    - pkgconfig(fuse)
    - pkgconfig(libsystemd)
    - gpgme-devel
    - libassuan-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # ostree is only used by flatpak in Solus, so nuke the unnecessary harmful bits.
    rm -rf $installdir/usr/{bin,lib}
    rm -rf $installdir/etc
