name       : ostree
version    : 2017.13
release    : 6
source     :
    - https://github.com/ostreedev/ostree/releases/download/v2017.13/libostree-2017.13.tar.xz : a8b06cd81b40072b127e9a8aa5d8c7a61bb44d8bc0e7f7b73dee2ce4d9b3e752
license    : LGPL-2.0
component  : system.utils
summary    : Git-like filesystem management
description: |
    Operating system and container binary deployment and upgrades
patterns   :
    - docs : /usr/share/man
builddeps  :
    - pkgconfig(e2p)
    - pkgconfig(fuse)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(liblzma)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libsystemd)
    - pkgconfig(mount)
    - pkgconfig(zlib)
    - docbook-xml
    - gpgme-devel
    - libassuan-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # ostree is only used by flatpak in Solus, so nuke the unnecessary harmful bits.
    rm -rf $installdir/usr/{bin,lib}
    rm -rf $installdir/usr/share/bash-completion/
    rm -rf $installdir/etc
