name       : ostree
version    : '2023.5'
release    : 19
source     :
    - https://github.com/ostreedev/ostree/releases/download/v2023.5/libostree-2023.5.tar.xz : bc593afb31fe1ac3d50419f917fafe321a0a3561d7bb2ba498a83740fe3adb14
license    : LGPL-2.0-or-later
component  : system.utils
summary    : Git-like filesystem management
description: |
    Operating system and container binary deployment and upgrades
patterns   :
    - docs : /usr/share/man
builddeps  :
    - pkgconfig(e2p)
    - pkgconfig(fuse)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gpgme)
    - pkgconfig(libarchive)
    - pkgconfig(libassuan)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(liblzma)
    - docbook-xml
setup      : |
    %configure --disable-static --with-soup3
build      : |
    %make
install    : |
    %make_install
    # Remove files only relevant to OSTree based OS images
    rm -r $installdir/etc/grub.d/
    rm -r $installdir/usr/lib
