name       : ostree
version    : '2019.3'
release    : 11
source     :
    - https://github.com/ostreedev/ostree/releases/download/v2019.3/libostree-2019.3.tar.xz : c09fe363bd2331b774050464547d4966bb32dabd3edfb03f0538c6c416f607e4
license    : LGPL-2.0-or-later
component  : system.utils
summary    : Git-like filesystem management
description: |
    Operating system and container binary deployment and upgrades
patterns   :
    - docs : /usr/share/man
builddeps  :
    - pkgconfig(e2p)
    - pkgconfig(fuse)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - docbook-xml
    - gpgme-devel
    - libassuan-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # Remove files only relevant to OSTree based OS images
    rm -r $installdir/etc/grub.d/
    rm -r $installdir/usr/lib
