name       : ostree
version    : 2018.7
release    : 8
source     :
    - https://github.com/ostreedev/ostree/releases/download/v2018.7/libostree-2018.7.tar.xz : 483e359fd934f3fb1abde2cd8ff9c5bccb97e2a37d52ed8bedfa9ab1290883d9
license    : LGPL-2.0-or-later
component  : system.utils
summary    : Git-like filesystem management
description: |
    Operating system and container binary deployment and upgrades
patterns   :
    - docs : /usr/share/man
builddeps  :
    - pkgconfig(e2p)
    - pkgconfig(fuse)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - docbook-xml
    - gpgme-devel
    - libassuan-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # Remove files only relevant to OSTree based OS images
    rm -r $installdir/etc/grub.d/
    rm -r $installdir/usr/lib
